Repository GSG-FC02/Resturant-Project, pull requests merged in 2021-03, with the labels that each got.

#3 write read me
  README.md
Labels: In progress

#16 create the home section
  images/aboutus.jpg
  images/background.jpg
  images/booking.png
  images/contact.jpg
  images/logo.png
  images/menu.jpg
  index.html
  style.css
Labels: Done

#11 create about section
  images/aboutus.jpg
  images/bookttable.jpg
  index.html
  style.css
Labels: Done

#14 create booking section
  index.html
  style.css
Labels: Done

#10 create main menu
  images/breakfast_menu.jpg
  images/cheesecake.jpg
  images/dinner_menu.jpg
  images/lunch_menu.jpg
  index.html
  style.css
Labels: Done

#15 Create contact section
  images/logo.png
  images/restaurant.jpg
  index.html
  style.css
Labels: Done

#18 create responsive sub menu by html and css
  menu.css
  menu.html
  style.css
Labels: Done

#20 modify css and html files
  index.html
  style.css
Labels: a waiting reviewe
